upstreams:
  groups:
    default:
      - 5.9.164.112
      - 1.1.1.1
      - tcp-tls:fdns1.dismail.de:853
      - https://dns.digitale-gesellschaft.ch/dns-query

blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - |
        # inline definition using YAML literal block scalar style
        # content is in plain domain list format
        someadsdomain.com
        anotheradsdomain.com
        *.wildcard.example.com # blocks wildcard.example.com and all subdomains
      - |
        # inline definition with a regex
        /^banners?[_.-]/
        xnxx.com
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  whiteLists:
    ads:
      #- whitelist.txt
      #- /path/to/file.txt
      - |
        # inline definition with YAML literal block scalar style
        whitelistdomain.com
  blockType: nxDomain
  blockTTL: 2h
  refreshPeriod: 12h
  downloadTimeout: 4m
  downloadAttempts: 5
  downloadCooldown: 10s
  failStartOnListError: false

prometheus:
  enable: true
  path: /metrics

ports:
  dns: 53
  http: 80

caching:
  minTime: -1
  maxTime: 0
  maxItemsCount: 0
  prefetching: true
  prefetchExpires: 24h
  prefetchThreshold: 2
  prefetchMaxItemsCount: 0

log:
  level: info
  timestamp: true
  privacy: false
