upstream:
  default:
    - 1.1.1.1
    - 1.0.0.1
    
upstreamTimeout: 2s
  blockType: nxDomain
  blockTTL: 2h
  refreshPeriod: 12h
  downloadTimeout: 4m
  downloadAttempts: 5
  downloadCooldown: 10s
  failStartOnListError: false

caching:
  minTime: -1
  maxTime: 0
  maxItemsCount: 0
  prefetching: true
  prefetchExpires: 24h
  prefetchThreshold: 2
  prefetchMaxItemsCount: 0

prometheus:
  enable: true
  path: /metrics

port: 53
httpPort: 4000
bootstrapDns: tcp+udp:1.1.1.1

logLevel: info
logFormat: text
logTimestamp: true
logPrivacy: false
